= Project Statistics Collection

----
Usage: p_stats [-hV] [-o=<outputFolder>] [-r=<resourcesFolder>] <inputFolder>
Calculate project stats
      <inputFolder>   Input folder.
  -h, --help          Show this help message and exit.
  -o, --output=<outputFolder>
                      Output folder.
  -r, --resources=<resourcesFolder>
                      Folder to download resources if not available.
  -V, --version       Print version information and exit.
----

The aim is to gather elementary statistics for the project for a comparison against link:https://github.com/github-linguist/linguist[GitHub Linguist].

== Understanding the Challenge with GitHub Linguist

A notable difficulty with **GitHub Linguist** lies in its complex set of rules for identifying files generated by tools, which are thus not considered part of the source code. Given the extensive range of tools GitHub accommodates, these rules sometimes fail to align with the requirements of our projects.

== Introducing `p_stats`

`p_stats` adopts a simpler approach. It utilizes a predefined list of directories to be excluded from the analysis, including:

----
".git", ".angular", ".gradle", "bin", "build", "node_modules", "target"
----

To propose additions to this list, please submit a pull request.

Furthermore, `p_stats` identifies the programming language of files based on their extension, leveraging the same database employed by **GitHub Linguist**. This database, contained within the `languages.yml` file, is accessible at https://raw.githubusercontent.com/github-linguist/linguist/master/lib/linguist/languages.yml

Should the `languages.yml` file be missing in the `resourcesFolder`, `p_stats` will automatically download it.

Given that file extensions in `languages.yml` may correspond to multiple languages, we have specified a list of primary languages to prioritize during language identification based on file extension:

----
"Java", "JavaScript", "TypeScript", "C#", "Python", "TSX", "JSON", "YAML",
"HTML", "XML", "XSLT", "CSS", "Less", "Sass", "SCSS", "Markdown", "Text",
"Objective-C", "SQL", "Java Server Pages"
----

Additionally, `p_stats` endeavors to detect subprojects within the `inputFolder` by identifying the presence of project descriptor files, currently including:

----
"package.json", "pom.xml", "build.gradle"
----

== Analytical Outputs

`p_stats` generates the following CSV files detailing the gathered statistics:

=== p_stats.csv

This CSV file encompasses basic statistics for all identified file extensions.

Fields include:

- *language*: The programming language determined from the file extension, as per `languages.yml`.
- *ext*: The file extension.
- *files*: The count of files with this extension found in `inputFolder`.
- *lines*: The aggregate number of lines across files with this extension.
- *size*: The cumulative size, in bytes, of files with this extension.
- *tests*: The count of tests identified for this language type, when applicable.

=== p_projects.csv

This CSV file lists all detected subprojects.

Fields include:

- *file*: The project descriptor.
- *project*: The path to the subproject.

=== p_errors.csv

This file records any errors encountered during the scan.

Fields include:

- *error*: The error type.
- *file*: The path to the file associated with the error.
